name: Archive package
on: push
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: montudor/action-zip@v1
      - run: zip -r package.zip *
        working-directory: src
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: src/package.zip

          
  
