name: Archive pipeline
on: push
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r package.zip src
      - uses: actions/upload-artifact@v2
        with:
          name: package.zip
  
