name: Archive package
on: push
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: src

          
  
